version: '2'

services:

  postgres_db:
    container_name: mednosis_db
    image: postgres
    environment:   # Set up postgres database name and password
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: mednosis
    ports:    # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - app-tier
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d


  python_app:
    container_name: mednosis_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    networks:
      - app-tier
    volumes:
      - ./static:/app/static
    command:
      tail -f /dev/null


networks:
  app-tier:
    driver: bridge
